"""UserModel back_populates=writer

Revision ID: 546b8b251532
Revises: 1b0ba19e7a66
Create Date: 2024-06-13 03:01:58.051512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546b8b251532'
down_revision: Union[str, None] = '1b0ba19e7a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
