"""commentModer ForeignKey to reviews

Revision ID: baa0f0258d4d
Revises: 546b8b251532
Create Date: 2024-06-13 03:04:21.294663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa0f0258d4d'
down_revision: Union[str, None] = '546b8b251532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_review_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'reviews', ['review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_review_id_fkey', 'comments', 'goods', ['review_id'], ['id'])
    # ### end Alembic commands ###
