"""del relationship to goods in CartModel

Revision ID: c1329c893ed5
Revises: 5e34854b2e62
Create Date: 2024-06-12 23:33:09.116145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1329c893ed5'
down_revision: Union[str, None] = '5e34854b2e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
